load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

cc_library(
    name = "jsonst",
    srcs = [
        "jsonst.c",
    ],
    hdrs = ["include/jsonst.h"],
    strip_include_prefix = "include",
    visibility = ["//visibility:public"],
)

cc_library(
    name = "jsonst_test_util",
    testonly = True,
    srcs = ["jsonst_test_util.cc"],
    hdrs = ["jsonst_test_util.h"],
    linkstatic = True,
    deps = [
        ":jsonst",
        ":jsonst_util",
        "@googletest//:gtest",
    ],
)

cc_test(
    name = "jsonst_test",
    size = "small",
    srcs = ["jsonst_test.cc"],
    # Work around test run .so loading issue.
    linkstatic = True,
    deps = [
        ":jsonst",
        ":jsonst_test_util",
        "@googletest//:gtest_main",
    ],
)

filegroup(
    name = "test_fuzz_crashes",
    srcs = glob([
        "testdata/crashes/*.json",
    ]),
    visibility = ["//visibility:public"],
)

cc_test(
    name = "jsonst_test_corpus",
    size = "small",
    srcs = ["jsonst_test_corpus.cc"],
    data = [
        ":test_fuzz_crashes",
        "@com_github_nst_json_test_suite//:test_parsing",
        "@com_github_nst_json_test_suite//:test_transform",
    ],
    # Work around test run .so loading issue.
    linkstatic = True,
    deps = [
        ":jsonst",
        ":jsonst_test_util",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "jsonst_util",
    srcs = ["jsonst_util.c"],
    hdrs = ["include/jsonst_util.h"],
    strip_include_prefix = "include",
    visibility = ["//visibility:public"],
    deps = [":jsonst"],
)

cc_library(
    name = "jsonst_cstd",
    hdrs = ["include/jsonst_cstd.h"],
    strip_include_prefix = "include",
    visibility = ["//visibility:public"],
    deps = [":jsonst"],
)

cc_test(
    name = "jsonst_cstd_test",
    size = "small",
    srcs = ["jsonst_cstd_test.cc"],
    data = ["testdata/test.json"],
    # Work around test run .so loading issue.
    linkstatic = True,
    deps = [
        ":jsonst_cstd",
        "@googletest//:gtest_main",
    ],
)
